name: Milind Sonavane
favicon: null
layout_spectrum: 0
typography_spectrum: 0.01336
title: Milind/Sonavane
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4cfc9'
    - '#000000'
    - '#a6a19b'
    - '#403732'
    - '#67625e'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
